// общее
import { NAVIGATION, HOW_IT_WORKS, CARD_SAMPLES, FREE_PLAN_FEATURES, PREMIUM_PLAN_FEATURES, QR_SIZES, CORNER_DOT_TYPES, CORNER_SQUARE_TYPES, DOT_TYPES } from "./common.ts";
export { NAVIGATION, HOW_IT_WORKS, CARD_SAMPLES, FREE_PLAN_FEATURES, PREMIUM_PLAN_FEATURES, QR_SIZES, CORNER_DOT_TYPES, CORNER_SQUARE_TYPES, DOT_TYPES };

// иконки
import { SiMessengerMax } from "./icons.ts";
export { SiMessengerMax }
